### PR TITLE
Make #current_comments and #current_comment public

### PR DESCRIPTION
**Pull request by KJTsanaktsidis**
I have a need to use ActiveRecord::Comments outside of the block-based system provided by #comment. I'm trying to correctly implement putting query comments on middleware. Using the wrapping method in that case results in deeper middlewares getting _all_ of the comments of the containing middlewares, which is a bit silly.

Instead, my middleware instrumentation code is managing comments with send(:current_comments) directly; pushing when calling a middleware, and then popping when that middleware returns & pushing again before calling the next middleware.

This means middlewares get only the comment for _that_ middleware, not all preceeding middlewares too.

### CODE REVIEW

**Comment by grosser** [comment]
so you are doing
```
def call
   comments << foo
  do stuff
  comments.pop
  yield
end
```
?
... would that not also work with a block helper
```
def call
  with_comment do
    do stuff
  end
  yield
end
```

**Comment by grosser** [comment]
generally pretty clean/simple so 👍 even though it seems like the `with_` api should be usable

**Comment by grosser** [comment]
0.7.0

**Comment by KJTsanaktsidis** [comment]
(Just to copy what I wrote in the other repo in here, since it's public here)

Yeah, unfortunately it has to be this way - my use case here is middleware instrumentation. We want to have the query comments & traces for a middleware to cover that middleware's execution, without covering where it does @app.call(env). We want two APM traces & query comment scopes & etc per middleware; one on request-side, and one on response-side.

To minimise the number of nested function-calls, each middleware is responsible for completing the spans of the one preceding it (and vice versa on the response side). You can't nest _just_ the request-side of a middleware you're wrapping in a call to `with do ... end` and then _just_ the response side in another `with do ... end`; it would also capture `@app.call(env)`.

**Pull request merged**
